import React, { useState, useEffect, useRef } from "react";
import axios from "axios";
import "../css/SingleEventPage.css";
import { useParams } from "react-router-dom";
import { useNavigate } from "react-router-dom";
import DonorTable from "../components/DonorTable";
import { IoArrowBack, IoLocationSharp, IoCalendarOutline } from "react-icons/io5";
import { MdDelete, MdEdit } from "react-icons/md";
import { FaUser, FaHospital, FaUsers, FaMapMarkedAlt } from "react-icons/fa";
import Topbar from "../components/Topbar";
import Sidebar from "../components/Sidebar";
import EventFormPopup from "../components/EventFormPopup";
import EditDonorTable from "../components/EditDonorTable";
import { FaSearch } from "react-icons/fa";

// API: '/events/:eventId'
function SingleEventPage() {
    // create variables to store event data and navigate to other pages
    const { eventId } = useParams();
    const navigate = useNavigate();

    // Event and donor list data
    const [event, setEvent] = useState([]);
    const [donors, setDonors] = useState([]);

    const [newEvent, setNewEvent] = useState(
        {
            name: "",
            raw_date: new Date(), // Date object for date picker
            city: "",
            location: "",
            medical_focus: "",
            capacity: "",
            coordinator: "",
            fundraiser: "",
            description: ""
        }
    ); // new event data for editing
    const [errors, setErrors] = useState({});
    const [userOptions, setUserOptions] = useState([]);

    // Flags to control the donor list UI states
    const [isFormVisible, setIsFormVisible] = useState(false); // indicates a saved donor list exists
    const [isGenerating, setIsGenerating] = useState(false);   // generating a new donor list from scratch
    const [isEditingFinalList, setIsEditingFinalList] = useState(false); // editing an existing donor list
    const [isAddingDonors, setIsAddingDonors] = useState(false); // adding extra donors during editing
    const [isPopupVisible, setIsPopupVisible] = useState(false); // popup for editing event details

    // Temporary donor list used during generation or editing
    const [tempDonorList, setTempDonorList] = useState([]);

    // State for top-level tabs
    const [topTab, setTopTab] = useState("autogenerated");

    // State for sub-tabs under "Autogenerated Donors"
    const [autoSubTab, setAutoSubTab] = useState("best");
    
    // States for tab switching and filtering in generation/adding mode
    const [searchName, setSearchName] = useState("");
    const [filterCity, setFilterCity] = useState("");
    const [filterMedicalFocus, setFilterMedicalFocus] = useState("");
    const [filterEngagement, setFilterEngagement] = useState("");
    const [filterSize, setFilterSize] = useState(0);
    
    // States for filter options
    const [cityOptions, setCityOptions] = useState([]);
    const [medicalFocusOptions, setMedicalFocusOptions] = useState([]);

    // Recommended donor lists (for generation or adding donors)
    const [bestMatchedDonors, setBestMatchedDonors] = useState([]); // best matched donors
    const [additionalDonors, setAdditionalDonors] = useState([]); // additional matched donors
    const [wasBestMatchedDonors, setWasBestMatchedDonors] = useState([]); // previously selected best matched donors
    const [wasAdditionalDonors, setWasAdditionalDonors] = useState([]); // previously selected additional matched donors
    const [matchedDonors, setMatchedDonors] = useState([]); // matched donors from search
    const [wasMatchedDonors, setWasMatchedDonors] = useState([]); // previously selected matched donors

    const [suggestions, setSuggestions] = useState([]); // suggestions for donor name search
    const [showSuggestions, setShowSuggestions] = useState(false); // show suggestions dropdown
    const [isLoading, setIsLoading] = useState(false);
    const dropdownRef = useRef(null); // Create a ref for the dropdown menu
    const [isSearchingByName, setIsSearchingByName] = useState(false); // Flag to indicate if searching by name

    function formatDateForInput(dateString) {
        const date = new Date(dateString);
        const year = date.getFullYear();
        const month = String(date.getMonth() + 1).padStart(2, '0');
        const day = String(date.getDate()).padStart(2, '0');
        
        return `${year}-${month}-${day}`;
      }

    // fetch event and donors data
    useEffect(() => {
        // create a function to fetch data
        const fetchData = async () => {
            try {
                // fetch the event data
                const eventResponse = await axios.get(`${process.env.REACT_APP_API_URL}/api/events/` + eventId + '/details');
                console.log(eventResponse.data);
                console.log("Raw date from backend:", eventResponse.data.date);
                setEvent(eventResponse.data);
                const data = eventResponse.data;
                setNewEvent({
                    name: data.name,
                    raw_date: formatDateForInput(data.raw_date), // Date object
                    city: data.city,
                    location: data.location,
                    medical_focus: data.medical_focus,
                    capacity: data.capacity,
                    coordinator: data.coordinator,
                    fundraiser: data.fundraiser,
                    description: data.detailed_info
                });

                // fetch the donors data
                const donorsResponse = await axios.get(`${process.env.REACT_APP_API_URL}/api/events/` + eventId + '/donors');
                console.log(donorsResponse.data);
                setDonors(donorsResponse.data || []);
                if (donorsResponse.data && donorsResponse.data.length > 0) {
                    setIsFormVisible(true);
                } else {
                    setIsFormVisible(false);
                }
            } catch (error) {
                // handle errors
                console.error("Failed to fetch event data:", error);
                alert(error.message);
                setEvent([]);
                setDonors([]);
                setIsFormVisible(false);
            }
        };
        // call the fetchEventData function
        fetchData();
    }, [eventId]);

    // New useEffect to set filters after event updates
    useEffect(() => {
        if (event && event.city) {
            setFilterCity(event.city);
            setFilterMedicalFocus(event.medical_focus);
            setFilterEngagement("Highly Engaged");
            setFilterSize(event.capacity || 0);
        }
    }, [event]);

    // useEffect: Fetch events and dropdown options on component mount
    useEffect(() => {
        axios
            .get(`${process.env.REACT_APP_API_URL}/api/events/medical-focuses`)
            .then((response) => setMedicalFocusOptions(response.data))
            .catch((err) => console.error("Error fetching medical focuses:", err));

        axios
            .get(`${process.env.REACT_APP_API_URL}/api/events/users`)
            .then((response) => setUserOptions(response.data))
            .catch((err) => console.error("Error fetching user names:", err));
    }, []);

    // delete the event
    const handleDelete = async () => {
        try {
            await axios.delete(`${process.env.REACT_APP_API_URL}/api/events/` + eventId);
            alert("Event deleted successfully!");
            navigate('/events');
        } catch (error) {
            // handle errors
            console.error("Failed to delete event:", error);
            alert(error.message);
        }
    };

    // Cancel handler: reset form and hide it
    const handleCancelEditEvent = () => {
        setIsPopupVisible(false);
        setNewEvent(event);
        setNewEvent({"raw_date": formatDateForInput(event.raw_date) });
        setErrors({});
    }
    // edit the event details
    // Validate all fields, and check capacity is a positive integer
    const validateForm = () => {
        let newErrors = {};
        Object.keys(newEvent).forEach((key) => {
            if (key !== "capacity" && !newEvent[key]) {
                newErrors[key] = "This field is required";
            }
        });
        if (newEvent.capacity === "" || newEvent.capacity === undefined || newEvent.capacity === null) {
            newErrors.capacity = "This field is required";
        } else if (Number(newEvent.capacity) <= 0) {
            newErrors.capacity = "Capacity must be a positive integer";
        } else if (Number(newEvent.capacity) < donors.length) {
            newErrors.capacity = "Capacity must be greater than or equal to the number of donors";
        }
        setErrors(newErrors);
        return Object.keys(newErrors).length === 0;
    };

    // Submit handler: validate + append event
    const handleEditEvent = async () => {
        if (!validateForm()) return;

        // Map frontend fields to backend keys.
        const payload = {
            name: newEvent.name,
            date: newEvent.raw_date, // Date object for date picker
            location: newEvent.location,
            city: newEvent.city,
            medical_focus: newEvent.medical_focus,
            capacity: parseInt(newEvent.capacity, 10),
            coordinator: newEvent.coordinator,
            fundraiser: newEvent.fundraiser,
            details: newEvent.description
        };

        try {
            console.log(payload);
            const response = await axios.put(`${process.env.REACT_APP_API_URL}/api/events/` + eventId, payload);
            console.log("Event added:", response.data);
            alert("Event updated successfully!");
            // Reset the form and hide it.
            setIsPopupVisible(false);
            setNewEvent(response.data);
            setNewEvent({"raw_date": response.data.raw_date});
            setErrors({});
            window.location.reload(); // Reload the page to reflect changes
        } catch (err) {
            console.error(err);
            alert(err.response?.data?.error || err.response?.data?.message || err.message);
        }
    };

    // export the donor list
    const handleExport = async () => {
        try {
            // check if there are donors to export
            if (donors.length === 0) {
                alert("No donors to export!");
                return;
            }
            // export the donors
            // get donors data
            const response = await axios.get(`${process.env.REACT_APP_API_URL}/api/events/` + eventId + '/donors/export', {
                responseType: 'blob',
            });
            // create a URL to download the file
            const url = window.URL.createObjectURL(new Blob([response.data]));
            const link = document.createElement('a');
            link.href = url;
            link.setAttribute('download', `donors_list_${eventId}.csv`);
            // click the link to download the file
            document.body.appendChild(link);
            link.click();
            // remove the link
            link.remove();
            URL.revokeObjectURL(url);

        } catch (error) {
            // handle errors
            console.error("Failed to export donors:", error);
            alert(error.message);
        }
    };

    // Fetch filter options
    useEffect(() => {
        const fetchFilterOptions = async () => {
          try {
            const citiesRes = await axios.get(`${process.env.REACT_APP_API_URL}/api/events/cities`);
            setCityOptions(citiesRes.data);
          } catch (error) {
            console.error("Failed to fetch city options:", error);
          }
          try {
            const focusRes = await axios.get(`${process.env.REACT_APP_API_URL}/api/events/medical-focuses`);
            setMedicalFocusOptions(focusRes.data);
          } catch (error) {
            console.error("Failed to fetch medical focus options:", error);
          }
        };
        fetchFilterOptions();
      }, []);

    // Generation mode: Create a new donor list
    const handleGenerateDonorList = () => {
        setIsGenerating(true);
        setTempDonorList([]);
        setTopTab("autogenerated");
        setAutoSubTab("best");
        generateRecommendedDonors();
    };

    // Fetch recommended donors from backend
    const generateRecommendedDonors = async () => {
        try {
            const response = await axios.get(`${process.env.REACT_APP_API_URL}/api/events/${eventId}/suggest-donors`, {
                params: {
                    city: filterCity,
                    medical_focus: filterMedicalFocus,
                    engagement: filterEngagement,
                    listSize: filterSize // parameter for list size
                }
            });
            const { best, additional } = response.data;
            setBestMatchedDonors(best);
            setAdditionalDonors(additional);
            setWasAdditionalDonors([]);
            setWasBestMatchedDonors([]);
        } catch (error) {
            console.error("Failed to fetch recommended donors:", error);
            alert("Failed to fetch recommended donors");
        }
    };

    // Search donors by name
    const handleSearchByName = async () => {
        try {
            const response = await axios.get(`${process.env.REACT_APP_API_URL}/api/events/${eventId}/donors/search`, {
                params: { name: searchName }
            });
            setIsSearchingByName(true);
            if (response.data.length > 0) {
                setMatchedDonors(response.data);
                setWasBestMatchedDonors([]);
            } else {
                setMatchedDonors([]);
                alert("No donors found matching the search criteria.");
            }
        } catch (error) {
            console.error("Donor search failed:", error);
            alert("Donor search failed");
        }
    };

    // Apply filters to regenerate donors
    const handleApplyFilters = async () => {
        // Validate the list size first
        const size = parseInt(filterSize);

        if (isNaN(size) || size <= 0) {
            alert("Please enter a valid list size greater than 0.");
            return; // Stop the function from continuing
        }
        
        try {
            console.log("Filters:", filterCity, filterMedicalFocus, filterEngagement, filterSize);
            const response = await axios.get(`${process.env.REACT_APP_API_URL}/api/events/${eventId}/suggest-donors`, {
                params: {
                    city: filterCity,
                    medical_focus: filterMedicalFocus,
                    engagement: filterEngagement,
                    listSize: filterSize
                }
            });
            console.log("Filtered donors:", response.data.best, response.data.additional);
            const { best, additional } = response.data;
            setBestMatchedDonors(best);
            setAdditionalDonors(additional);
            alert("Donors regenerated successfully!");
        } catch (error) {
            console.error("Failed to fetch donor suggestions:", error);
            alert("Failed to fetch donor suggestions");
        }
    };

    // Add a donor to the temporary list
    const handleAddDonor = async (donor, options = { showAlert: true }) => {
        try {
            // Create a donorIdArray for the backend without mutating donor.id
            const donorIdArray = Array.isArray(donor.id) ? donor.id : [donor.id]

            // send a request to the backend to add the donor temporarily
            await axios.post(`${process.env.REACT_APP_API_URL}/api/events/${eventId}/donors/add`, { donorIds: donorIdArray });
            
            if (!tempDonorList.some(d => d.id === donor.id)) {
                setTempDonorList(prev => [...prev, donor]);

                // filter out the selected donor from the recommended lists
                if (bestMatchedDonors.some(d => d.id === donor.id)) {
                    setWasBestMatchedDonors(prev => [...prev, donor]);
                    setBestMatchedDonors(prev => prev.filter(d => d.id !== donor.id));
                }
                if (additionalDonors.some(d => d.id === donor.id)) {
                    setWasAdditionalDonors(prev => [...prev, donor]);
                    setAdditionalDonors(prev => prev.filter(d => d.id !== donor.id));
                }
                if (matchedDonors.some(d => d.id === donor.id)) {
                    setWasMatchedDonors(prev => [...prev, donor]);
                    setMatchedDonors(prev => prev.filter(d => d.id !== donor.id));
                }
            }
            // Show alert if donor added successfully
            if (options.showAlert) {
                alert("Donor added temporarily!");
            }
        } catch (error) {
            console.error("Failed to add donor temporarily:", error);
            alert("Failed to add donor");
        }
    };

    // Bulk add donors to the temporary list
    const handleBulkAddDonors = async (donorArray) => {
        try {
            for (const donor of donorArray) {
                await handleAddDonor(donor, { showAlert: false }); // pass a flag to suppress alert
            }
            alert("All selected donors added temporarily!");
        } catch (error) {
            console.error("Bulk add failed:", error);
            alert("Failed to add some donors");
        }
    };

    // Remove a donor from the temporary list
    const handleRemoveDonor = async (id) => {
        try {
            await axios.post(`${process.env.REACT_APP_API_URL}/api/events/${eventId}/donors/remove`, { donorId: id });
            alert("Donor removed temporarily!");
            setTempDonorList(tempDonorList.filter(d => d.id !== id));
            if (wasBestMatchedDonors.some(d => d.id === id)) {
                const donor = wasBestMatchedDonors.find(d => d.id === id);
                setBestMatchedDonors([...bestMatchedDonors, donor]);
                setWasBestMatchedDonors(wasBestMatchedDonors.filter(d => d.id !== id));
            }
            if (wasAdditionalDonors.some(d => d.id === id)) {
                const donor = wasAdditionalDonors.find(d => d.id === id);
                setAdditionalDonors([...additionalDonors, donor]);
                setWasAdditionalDonors(wasAdditionalDonors.filter(d => d.id !== id));
            }
            if (wasMatchedDonors.some(d => d.id === id)) {
                const donor = wasMatchedDonors.find(d => d.id === id);
                setMatchedDonors([...matchedDonors, donor]);
                setWasMatchedDonors(wasMatchedDonors.filter(d => d.id !== id));
            }
        } catch (error) {
            console.error("Failed to remove donor temporarily:", error);
            alert("Failed to remove donor");
        }
    };

    // Cancel generating a new list
    const handleCancelGenerate = async () => {
        try {
            await axios.post(`${process.env.REACT_APP_API_URL}/api/events/${eventId}/donors/cancel`);
            setIsGenerating(false);
            setTempDonorList([]);

            // reset filters to default values
            setFilterCity(event.city);
            setFilterMedicalFocus(event.medical_focus);
            setFilterEngagement("Highly Engaged");
            setFilterSize(event.capacity || 0);
            setSearchName("");
            setIsSearchingByName(false);
            
            // reset all donor lists
            setMatchedDonors([]);
            setBestMatchedDonors([]);
            setAdditionalDonors([]);
            setWasBestMatchedDonors([]);
            setWasAdditionalDonors([]);
            setWasMatchedDonors([]);
            setSuggestions([]);
        } catch (error) {
            console.error("Failed to cancel donor edits:", error);
            alert("Failed to cancel donor edits");
        }
    };

    // Save generated donor list as final list
    const handleSaveGenerate = async () => {
        try {
            await axios.post(`${process.env.REACT_APP_API_URL}/api/events/${eventId}/donors/save`);
            const donorsResponse = await axios.get(`${process.env.REACT_APP_API_URL}/api/events/${eventId}/donors`);
            setDonors(donorsResponse.data || []);
            setIsGenerating(false);
            setIsFormVisible(true);
            setSearchName("");
            setWasAdditionalDonors([]);
            setWasBestMatchedDonors([]);
            setWasMatchedDonors([]);
            window.location.reload(); // Reload the page to reflect changes
            alert("Donor list generated and saved!");
        } catch (error) {
            console.error("Failed to save donor list:", error);
            alert("Failed to save donor list");
        }
    };

    // Edit an existing donor list (initially for deletion only)
    const handleEditDonorList = () => {
        setIsEditingFinalList(true);
        // Start editing with the saved donor list
        setTempDonorList(donors);
    };

    // Cancel editing
    const handleCancelEdit = async () => {
        try {
            await axios.post(`${process.env.REACT_APP_API_URL}/api/events/${eventId}/donors/cancel`);
            setIsEditingFinalList(false);
            setTempDonorList([]);
            setIsAddingDonors(false); // also cancel any add donors UI if open
            // reset filters to default values
            setFilterCity(event.city);
            setFilterMedicalFocus(event.medical_focus);
            setFilterEngagement("Highly Engaged");
            setFilterSize(event.capacity || 0);
            setSearchName("");
            setIsSearchingByName(false);
            
            // reset all donor lists
            setMatchedDonors([]);
            setBestMatchedDonors([]);
            setAdditionalDonors([]);
            setWasBestMatchedDonors([]);
            setWasAdditionalDonors([]);
            setWasMatchedDonors([]);
            setSuggestions([]);
        } catch (error) {
            console.error("Failed to cancel donor edits:", error);
            alert("Failed to cancel donor edits");
        }
    };

    // Save edited donor list
    const handleSaveEdit = async () => {
        try {
            await axios.post(`${process.env.REACT_APP_API_URL}/api/events/${eventId}/donors/save`);
            const donorsResponse = await axios.get(`${process.env.REACT_APP_API_URL}/api/events/${eventId}/donors`);
            setDonors(donorsResponse.data || []);
            setIsEditingFinalList(false);
            setIsAddingDonors(false);
            setSearchName("");
            setWasAdditionalDonors([]);
            setWasBestMatchedDonors([]);
            setWasMatchedDonors([]);
            alert("Donor list updated!");
            window.location.reload(); // Reload the page to reflect changes
        } catch (error) {
            console.error("Failed to update donor list:", error);
            alert("Failed to update donor list");
        }
    };

    // Handle "Add Donors" action in edit mode:
    // Show the recommended donor lists (similar to generate mode)
    const handleShowAddDonors = () => {
        setIsAddingDonors(true);
        setTopTab("autogenerated");
        setAutoSubTab("best");
        generateRecommendedDonors();
    };

    // Debounce function to limit API calls while typing
    const debounce = (func, delay) => {
        let timeoutId;
        return (...args) => {
        clearTimeout(timeoutId);
        timeoutId = setTimeout(() => func(...args), delay);
        };
    };
  
    // Create a debounced search function
    const debouncedSearch = debounce(async (value) => {
        if (value.length < 2) return;
        
        setIsLoading(true);
        try {
        const response = await axios.get(`${process.env.REACT_APP_API_URL}/api/events/${eventId}/donors/search`, {
            params: { name: value }
        });
        setSuggestions(response.data);
        setShowSuggestions(true);
        } catch (error) {
        console.error("Suggestions fetch failed:", error);
        setSuggestions([]);
        } finally {
        setIsLoading(false);
        }
    }, 300); // 300ms delay
    
    // Handle input changes
    const handleSearchInputChange = (e) => {
        const value = e.target.value;
        setSearchName(value);
        
        if (value.length >= 2) {
        debouncedSearch(value);
        } else {
        setSuggestions([]);
        setShowSuggestions(false);
        }
    };
    
    // Function to handle selection of a suggestion
    const handleSelectSuggestion = (donor) => {
        setSearchName(donor.name);
        setShowSuggestions(false);
        setMatchedDonors([donor]); // Immediately show this donor in results
    };

    // Handle clicks outside the dropdown
    useEffect(() => {
        function handleClickOutside(event) {
        // If click is outside the dropdown, hide it
        if (dropdownRef.current && !dropdownRef.current.contains(event.target)) {
            setShowSuggestions(false);
        }
        }
        
        // Add event listener when component mounts
        document.addEventListener("mousedown", handleClickOutside);
        
        // Clean up event listener when component unmounts
        return () => {
        document.removeEventListener("mousedown", handleClickOutside);
        };
    }, []);

    // Rendering
    if (!event) {
        return <div>Loading...</div>;
    }

    return (
        <div className="app-container">
            <Topbar />
            <div className="main-content">
                <Sidebar />
                <div className="content">
                    <div className="event-container">
                        <button className="back-button" onClick={() => navigate("/events")}>
                            <IoArrowBack className="icon"/>
                        </button>
                        <div className="event-container-main">
                            <div className="event-header">
                                <h1>{event.name}</h1>
                                <div className="donor-edit-buttons">
                                    <button className="delete-button" onClick={handleDelete}>
                                        <MdDelete className="icon"/>  Delete
                                    </button>
                                    <button className="edit-button" onClick={() => {setIsPopupVisible(true);}}>
                                        <MdEdit className="icon"/>  Edit
                                    </button>
                                </div>
                            </div>
                            <div className="event-details-grid">
                                <div className="event-card">
                                    <IoCalendarOutline className="icon" />
                                    <div className="event-card-content">
                                        <p>Event Date</p>
                                        <strong>{event.date}</strong>
                                    </div>
                                </div>
                                <div className="event-card">
                                    <IoLocationSharp className="icon" />
                                    <div className="event-card-content">
                                        <p>Event Location</p>
                                        <strong>{event.location}</strong>
                                    </div>
                                </div>
                                <div className="event-card">
                                    <FaMapMarkedAlt className="icon" />
                                    <div className="event-card-content">
                                        <p>Event City</p>
                                        <strong>{event.city}</strong>
                                    </div>
                                </div>
                                <div className="event-card">
                                    <FaHospital className="icon" />
                                    <div className="event-card-content">
                                        <p>Medical Focus</p>
                                        <span className="medical-focus">{event.medical_focus}</span>
                                    </div>
                                </div>
                                <div className="event-card">
                                    <FaUsers className="icon" />
                                    <div className="event-card-content">
                                        <p>Capacity</p>
                                        <strong>{event.capacity}</strong>
                                    </div>
                                </div>
                                <div className="event-card">
                                    <FaUser className="icon" />
                                    <div className="event-card-content">
                                        <p>Coordinator</p>
                                        <strong>{event.coordinator}</strong>
                                    </div>
                                </div>
                                <div className="event-card">
                                    <FaUser className="icon" />
                                    <div className="event-card-content">
                                        <p>Fundraiser</p>
                                        <strong>{event.fundraiser}</strong>
                                    </div>
                                </div>
                            </div>
                            <div className="detailed-info">
                                <h3>Detailed Information</h3>
                                <p>{event.detailed_info}</p>
                            </div>
                        </div>

                        <div className="donor-container">
                            {/* A) No donor list exists: show Generate button */}
                            {!isFormVisible && !isGenerating && !isEditingFinalList && (
                                <div className="generate-button">
                                    <button onClick={handleGenerateDonorList}>
                                        Generate Donor List
                                    </button>
                                </div>
                            )}
                            {/* Update reset*/}
                            {/* B) Generating a new donor list from scratch */}
                            {isGenerating && (
                                <div className="donor-edit-container">
                                    <h2>Generate Donor List</h2>

                                    <div className="donor-generate-form">
                                        {/* Top-Level Tabs */}
                                        <div className="gen-top-tabs">
                                            <button
                                                className={topTab === "autogenerated" ? "active" : ""}
                                                onClick={() => setTopTab("autogenerated")}
                                            >
                                                Autogenerated Donors
                                            </button>
                                            <button
                                                className={topTab === "search" ? "active" : ""}
                                                onClick={() => setTopTab("search")}
                                            >
                                                Search Donors
                                            </button>
                                        </div>

                                        {/* --- AUTOGENERATED DONORS TAB --- */}
                                        {topTab === "autogenerated" && (
                                        <div className="autogenerated-content">
                                            {/* Filters + Regenerate Button */}
                                            <div className="filters-row">
                                                <select value={filterCity} onChange={(e) => setFilterCity(e.target.value)}>
                                                    {cityOptions.map((city, idx) => (
                                                    <option key={idx} value={city}>
                                                        {city}
                                                    </option>
                                                    ))}
                                                </select>
                                                <select
                                                    value={filterMedicalFocus}
                                                    onChange={(e) => setFilterMedicalFocus(e.target.value)}
                                                >
                                                    {medicalFocusOptions.map((focus, idx) => (
                                                    <option key={idx} value={focus}>
                                                            {focus}
                                                    </option>
                                                    ))}
                                                </select>
                                                <select
                                                    value={filterEngagement}
                                                    onChange={(e) => setFilterEngagement(e.target.value)}
                                                >
                                                    <option value="Highly Engaged">Highly Engaged</option>
                                                    <option value="Moderately Engaged">Moderately Engaged</option>
                                                    <option value="Rarely Engaged">Rarely Engaged</option>
                                                </select>
                                                <span className="info-icon" 
                                                title={"Engagement level is based on total donations, event subscriptions, and donor status (deceased or excluded)."}>ⓘ</span>
                                                <input
                                                    value={filterSize}
                                                    onChange={(e) => setFilterSize(e.target.value)}
                                                    type="number"
                                                    min="1"
                                                    placeholder="List Size"
                                                />
                                                <span className="info-icon" 
                                                title={"The number of donors to be matched in each list"}>ⓘ</span>
                                                <button onClick={handleApplyFilters}>Regenerate</button>
                                            </div>

                                            {/* Sub-Tabs: Best Matched vs Additional Matches */}
                                            <div className="sub-tabs">
                                                <button
                                                    className={autoSubTab === "best" ? "active" : ""}
                                                    onClick={() => setAutoSubTab("best")}
                                                >
                                                    Best Matched Donors
                                                </button>
                                                <button
                                                    className={autoSubTab === "additional" ? "active" : ""}
                                                    onClick={() => setAutoSubTab("additional")}
                                                >
                                                    Additional Matches
                                                </button>
                                            </div>

                                            {/* Donor Tables */}
                                            {autoSubTab === "best" && (
                                            <EditDonorTable
                                                donors={bestMatchedDonors}
                                                showActions={true}
                                                handleAddDonor={handleAddDonor}
                                                handleBulkAddDonors={handleBulkAddDonors}
                                            />
                                            )}
                                            {autoSubTab === "additional" && (
                                            <EditDonorTable
                                                donors={additionalDonors}
                                                showActions={true}
                                                handleAddDonor={handleAddDonor}
                                                handleBulkAddDonors={handleBulkAddDonors}
                                            />
                                            )}
                                        </div>
                                        )}

                                        {/* --- SEARCH DONORS TAB --- */}
                                        {topTab === "search" && (
                                        <div className="search-content">
                                            <div className="search-name-bar">
                                                <div className="autocomplete-container">
                                                    <div className="search-input-wrapper">
                                                        <FaSearch className="search-icon" />
                                                        <input
                                                        type="text"
                                                        value={searchName}
                                                        onChange={handleSearchInputChange}
                                                        placeholder="Search donor name"
                                                        />
                                                    </div>

                                                    {isLoading && (
                                                        <div className="loading-indicator">
                                                        <div className="spinner"></div>
                                                        </div>
                                                    )}

                                                    {showSuggestions && suggestions.length > 0 && (
                                                    <div 
                                                        className="suggestions-dropdown"
                                                        ref={dropdownRef} // Add the ref here
                                                    >
                                                        {suggestions.map((suggestion) => (
                                                        <div 
                                                            key={suggestion.id} 
                                                            className="suggestion-item"
                                                            onClick={() => handleSelectSuggestion(suggestion)}
                                                        >
                                                            {suggestion.name}
                                                        </div>
                                                        ))}
                                                    </div>
                                                    )}
                                                </div>
                                                <button onClick={handleSearchByName}>Search</button>
                                            </div>
                                        
                                            {matchedDonors.length > 0 ? (
                                            <div>
                                                <h3>Result:</h3>
                                                <EditDonorTable
                                                donors={matchedDonors}
                                                showActions={true}
                                                handleAddDonor={handleAddDonor}
                                                handleBulkAddDonors={handleBulkAddDonors}
                                                />
                                            </div>
                                            ) : (
                                                isSearchingByName ? 
                                                    <p>No donors found.</p> : null
                                            )}
                                        </div>
                                        )}

                                        {/* Temporary Donor List */}
                                        <div className="temp-donor-list">
                                        <h3>Temporary Donor List</h3>
                                        {tempDonorList.length === 0 ? (
                                            <p>No donors added yet</p>
                                        ) : (
                                            <DonorTable
                                            donors={tempDonorList}
                                            showActions={true}
                                            handleRemoveDonor={handleRemoveDonor}
                                            />
                                        )}
                                        </div>

                                        {/* Bottom Action Buttons */}
                                        <div className="bottom-buttons">
                                        <button className="cancel-button" onClick={handleCancelGenerate}>Cancel</button>
                                        <button onClick={handleSaveGenerate}>Save</button>
                                        </div>
                                    </div>
                                </div>
                                )}

                            {/* C) Finalized donor list view (non-editing) */}
                            {isFormVisible && !isEditingFinalList &&  (
                                <div className="donor-edit-container">
                                    <div className="donor-header">
                                        <h2>Donor List</h2>
                                        <div className="donor-buttons">                            
                                            <button onClick={handleEditDonorList}>Edit</button>
                                            <button onClick={handleExport}>Export CSV</button>
                                        </div>
                                    </div>
                                    <DonorTable donors={donors} showActions={false} />
                                </div>
                            )}

                            {/* D) Editing the finalized donor list */}
                            {isFormVisible && isEditingFinalList && (
                                <div className="donor-edit-form">
                                    <div className="donor-header">
                                        <h2>Edit Donor List</h2>
                                        {!isAddingDonors && (
                                            <div className="add-donors-button">
                                            <button onClick={handleShowAddDonors}>+ Add Donors</button>
                                            </div>
                                    )}
                                    </div>

                                    {isAddingDonors && (
                                    <div className="donor-add-form">
                                        {/* Top-Level Tabs */}
                                        <div className="gen-top-tabs">
                                        <button
                                            className={topTab === "autogenerated" ? "active" : ""}
                                            onClick={() => setTopTab("autogenerated")}
                                        >
                                            Autogenerated Donors
                                        </button>
                                        <button
                                            className={topTab === "search" ? "active" : ""}
                                            onClick={() => setTopTab("search")}
                                        >
                                            Search Donors
                                        </button>
                                        </div>

                                        {/* Autogenerated Donors Content */}
                                        {topTab === "autogenerated" && (
                                        <div className="autogenerated-content">
                                            <div className="filters-row">
                                            <select value={filterCity} onChange={(e) => setFilterCity(e.target.value)}>
                                                {cityOptions.map((city, idx) => (
                                                <option key={idx} value={city}>{city}</option>
                                                ))}
                                            </select>
                                            <select value={filterMedicalFocus} onChange={(e) => setFilterMedicalFocus(e.target.value)}>
                                                {medicalFocusOptions.map((focus, idx) => (
                                                <option key={idx} value={focus}>{focus}</option>
                                                ))}
                                            </select>
                                            <select value={filterEngagement} onChange={(e) => setFilterEngagement(e.target.value)}>
                                                <option value="Highly Engaged">Highly Engaged</option>
                                                <option value="Moderately Engaged">Moderately Engaged</option>
                                                <option value="Rarely Engaged">Rarely Engaged</option>
                                            </select>
                                            <span className="info-icon" 
                                                title={"Engagement level is based on total donations, event subscriptions, and donor status (deceased or excluded)."}>ⓘ</span>
                                            <input
                                                    value={filterSize}
                                                    onChange={(e) => setFilterSize(e.target.value)}
                                                    type="number"
                                                    min="1"
                                                    placeholder="List Size"
                                            />
                                            <span className="info-icon" 
                                                title={"The number of donors to be matched in each list"}>ⓘ</span>
                                            <button onClick={handleApplyFilters}>Regenerate</button>
                                            </div>

                                            <div className="sub-tabs">
                                            <button
                                                className={autoSubTab === "best" ? "active" : ""}
                                                onClick={() => setAutoSubTab("best")}
                                            >
                                                Best Matched Donors
                                            </button>
                                            <button
                                                className={autoSubTab === "additional" ? "active" : ""}
                                                onClick={() => setAutoSubTab("additional")}
                                            >
                                                Additional Matches
                                            </button>
                                            </div>

                                            {autoSubTab === "best" && (
                                            <EditDonorTable 
                                                donors={bestMatchedDonors} 
                                                showActions={true} 
                                                handleAddDonor={handleAddDonor}
                                                handleBulkAddDonors={handleBulkAddDonors} 
                                            />
                                            )}
                                            {autoSubTab === "additional" && (
                                            <EditDonorTable 
                                                donors={additionalDonors} 
                                                showActions={true} 
                                                handleAddDonor={handleAddDonor}
                                                handleBulkAddDonors={handleBulkAddDonors} 
                                            />
                                            )}
                                        </div>
                                        )}

                                        {/* Search Donors Content */}
                                        {topTab === "search" && (
                                        <div className="search-content">
                                            <div className="search-name-bar">
                                                <div className="autocomplete-container">
                                                    <div className="search-input-wrapper">
                                                        <FaSearch className="search-icon" />
                                                        <input
                                                        type="text"
                                                        value={searchName}
                                                        onChange={handleSearchInputChange}
                                                        placeholder="Search donor name"
                                                        />
                                                    </div>

                                                    {isLoading && (
                                                        <div className="loading-indicator">
                                                        <div className="spinner"></div>
                                                        </div>
                                                    )}

                                                    {showSuggestions && suggestions.length > 0 && (
                                                    <div 
                                                        className="suggestions-dropdown"
                                                        ref={dropdownRef} // Add the ref here
                                                    >
                                                        {suggestions.map((suggestion) => (
                                                        <div 
                                                            key={suggestion.id} 
                                                            className="suggestion-item"
                                                            onClick={() => handleSelectSuggestion(suggestion)}
                                                        >
                                                            {suggestion.name}
                                                        </div>
                                                        ))}
                                                    </div>
                                                    )}
                                                </div>
                                                <button onClick={handleSearchByName}>Search</button>
                                            </div>
                                        
                                            {matchedDonors.length > 0 ? (
                                            <div>
                                                <h3>Result:</h3>
                                                <EditDonorTable
                                                    donors={matchedDonors}
                                                    showActions={true}
                                                    handleAddDonor={handleAddDonor}
                                                    handleBulkAddDonors={handleBulkAddDonors}
                                                />
                                            </div>
                                            ) : (
                                                isSearchingByName ? 
                                                    <p>No donors found.</p> : null
                                            )}
                                        </div>
                                        )}
                                        {/* Donor Table shown inside the tab when adding donors */}
                                        <div className="temp-donor-list">
                                        <h3>Temporary Donor List</h3>
                                        {tempDonorList.length === 0 ? (
                                            <p>No donors added yet</p>
                                        ) : (
                                            <DonorTable
                                                donors={tempDonorList}
                                                showActions={true}
                                                handleRemoveDonor={handleRemoveDonor}
                                            />
                                        )}
                                        </div>
                                    </div>
                                    )}
                                    {!isAddingDonors && (
                                        <DonorTable
                                            donors={tempDonorList}
                                            showActions={true}
                                            handleRemoveDonor={handleRemoveDonor}
                                        />
                                    )}
                                    <div className="donor-edit-actions">
                                        <button className="cancel-button" onClick={handleCancelEdit}>Cancel</button>
                                        <button onClick={handleSaveEdit}>Save</button>
                                    </div>
                                </div>
                            )}
                        </div>
                    </div>

                    {isPopupVisible && (
                        <EventFormPopup
                            isVisible={isPopupVisible}
                            mode="edit"
                            eventData={newEvent}
                            setEventData={setNewEvent}
                            medicalFocusOptions={medicalFocusOptions}
                            userOptions={userOptions}
                            errors={errors}
                            onCancel={handleCancelEditEvent}
                            onSubmit={handleEditEvent}
                        />
                    )}
                </div>
            </div>
        </div>
    );
}

export default SingleEventPage;